import { Button, FormElement, Textarea } from '@nextui-org/react'
import type { NextPage } from 'next'
import ReactPlayer from 'react-player'
import Head from 'next/head'
import { ChangeEvent, useState, useCallback } from 'react'

import { QUOTATIONS } from '../constants'
import { getRandomArrayItem } from '../utils/getRandomArrayItem'

const Home: NextPage = () => {
    const [showPlayer, setShowPlayer] = useState(false)

    const voices =
        typeof window !== 'undefined'
            ? window.speechSynthesis.getVoices()
            : undefined

    const [text, setText] = useState('')

    const onTextChange = (e: ChangeEvent<FormElement>) => {
        setText(e.target.value)
    }

    const sayText = useCallback(() => {
        const utter = new SpeechSynthesisUtterance(text)
        const voice = voices?.find((voice) => voice.voiceURI === 'Yuri')

        if (!!voice) {
            utter.voice = voice
            utter.rate = 0.9
            window.speechSynthesis.speak(utter)
        }

        utter.onend = () => {
            setShowPlayer(true)
        }
    }, [text, voices])

    const onVideoEnded = useCallback(() => {
        setShowPlayer(false)
    }, [])

    const makeRandomText = useCallback(() => {
        const randomText = getRandomArrayItem(QUOTATIONS)
        setText(randomText)
    }, [])

    return (
        <div className="h-screen flex flex-col justify-between items-center">
            <Head>
                <title>Создай свою цитату, волк</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="flex flex-col items-center justify-center">
                <h1 className="text-3xl mt-20 mb-4">
                    Создай свою цитату{' '}
                    <a href="https://www.google.com/search?q=%D1%86%D0%B8%D1%82%D0%B0%D1%82%D0%B0+%D0%B2%D0%BE%D0%BB%D0%BA%D0%B0">
                        волка
                    </a>
                </h1>
                <Textarea
                    placeholder="Безумно можно быть первым"
                    className="mb-4 min-w-[400px]"
                    onChange={onTextChange}
                    value={text}
                />
                <Button onClick={sayText}>создать</Button>
                <Button light onClick={makeRandomText}>
                    сгенерируйте за меня
                </Button>
                {showPlayer && (
                    <ReactPlayer
                        url="/video.mp4"
                        playing={showPlayer}
                        onEnded={onVideoEnded}
                    />
                )}
            </main>

            <footer className="p-4">
                <a
                    href="https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=43s"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    сделано Сашкой
                </a>
            </footer>
        </div>
    )
}

export default Home
